<a href="https://www.kaggle.com/code/takrimulalam/spammaildetection?scriptVersionId=249055976" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/spam-email-classification/email.csv


In [24]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import MultinomialNB
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

In [3]:
data_frame = pd.read_csv("/kaggle/input/spam-email-classification/email.csv")

In [4]:
data_frame.shape

(5573, 2)

In [5]:
data_frame.columns

Index(['Category', 'Message'], dtype='object')

In [6]:
data_frame.drop_duplicates(inplace =True)

In [7]:
data_frame.shape

(5158, 2)

In [8]:
x = data_frame["Message"]

In [9]:
y = data_frame["Category"]

In [10]:
x

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
5572                                      isActive:false}
Name: Message, Length: 5158, dtype: object

In [11]:
y

0                  ham
1                  ham
2                 spam
3                  ham
4                  ham
             ...      
5568               ham
5569               ham
5570               ham
5571               ham
5572    {"mode":"full"
Name: Category, Length: 5158, dtype: object

In [12]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=0)

In [13]:
vectorizer = CountVectorizer()
X_train = vectorizer.fit_transform(X_train)

In [14]:
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)

In [15]:
X_train.toarray(), y_train

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([1, 0, 0, ..., 0, 0, 0]))

In [16]:
model = MultinomialNB()
model.fit(X_train,y_train)

MultinomialNB()

In [17]:
X_test = vectorizer.transform(X_test)
y_test = label_encoder.transform(y_test)

In [18]:
model.score(X_test,y_test)

0.9844961240310077

In [20]:
y_pred = model.predict(X_test)

In [22]:
y_pred

array([0, 0, 1, ..., 0, 0, 0])

In [25]:
joblib.dump(model,"spam_model.pkl")

['spam_model.pkl']